FROM golang:1.25.11-trixie AS builder

WORKDIR /app
COPY go.mod main.go client.go ./
RUN go install github.com/go-delve/delve/cmd/dlv@latest && \
    CGO_ENABLED=0 GOOS=linux go build -gcflags="all=-N -l" -o go-simple-chat

FROM golang:1.25.11-trixie
WORKDIR /app
COPY --from=builder /go/bin/dlv /dlv
COPY --from=builder /app/main.go /app/client.go ./
COPY --from=builder /app/go-simple-chat /
EXPOSE 9999 2345

ENTRYPOINT ["/dlv", "exec", "/go-simple-chat", "--headless", "--listen=0.0.0.0:2345", "--api-version=2"]

